---
title: "Stat424 2016 Spring"
author: "Song Wang"
output: html_document
---

#### My Name is Song Wang, a fourth-year PhD student at Stat Dept. I am TA for stat 424 -- experiment design -- 2016 srping. This is the homepage for that course. Here I will post my handouts as well as R codes.

#### Office hours :11am -12pm Mondays and 3-4pm Wednesdays.


### Here are the handouts and codes:

Discussion 1

- [disc1 handout](A_Brief_Intro_to_R.html)
 
- [dataset for disc1](mtcars.csv)

Discussion 2 
 
- [disc2 handout](disc2.pdf)
- [code for disc2](Sol2.html)

 Discussion 3 
 
- [disc3 handout](disc3.pdf)
- [code for disc3](disc3.R)
- [code for project1](project1.R)

Discussion 4
 
- [disc4 handout](disc4.pdf)
- [code for disc4](disc4.R): using **aov** to solve randomized block design block, and  a little bit about package *dplyr*.

Discussion 5
 
- [disc5 handout](disc5.pdf)
- [code for disc5](disc5.html): more on *aov* and some visualization
- [Some notes on RCBD](RCBD.pdf) some use materials on randomized block desgin.

Discussion 6
 
- No handout this time, cover problems from exam and Question 4 page 224.
- [code for disc6](disc6.html): use R to calculate main effects, interaction effects. better use hand.
- [exam solution](Exam 1 - Review - Solutions.docx) Solutions for exam 1.


Discussion 7
 
- No handout this time, cover problems from exam and homework questions.

Discussion 8 

- [disc8 handout](disc8.pdf)

Discussion 9 

- [disc9 handout](disc9.pdf)

Discussion 10 

- [disc10 handout](disc10.pdf): review on fractional factorial design and data boxcox transformation
- [R code for data transformation](disc10.html)


Discussion 11 

- [disc11 handout](disc11.pdf): example on hand calcualation aboutsplit-plot design.
- [R code for split-plot design and hierarchical design](disc11_split-plot.html)
- [Some theory split-plot design](sptheory.pdf)


Discussion 12 

- [disc12 handout](disc12.pdf): example on multicollinearity and centerization in regression.